### ISSUE TITLE
Low Latency doesnt work

### ISSUE THREAD

**Issue by Fan4eGGG** [radiance-project/ear-web#14]
Do you know why Low Latency is not working? i was waiting for this app for this feature. i use sound in Opera, but in Chrome it doesn’t work either.
im using the "application" version on my desctop tho

what could it be?

**Comment by Lisra-git** [comment]
> Do you know why Low Latency is not working? i was waiting for this app for this feature. i use sound in Opera, but in Chrome it doesn’t work either. im using the "application" version on my desctop tho
> 
> what could it be?

Low Latency is working just like in Nothing X, if you think it's not working it might be that your device simply doesn't support low latency Bluetooth connection

**Comment by Fan4eGGG** [comment]
>  your device simply doesn't support low latency Bluetooth connection

why then my enco free 3 headphones work fine low latency mode?
it's definitely a problem with the app x or whatever it's called.

**Comment by Lisra-git** [comment]
> > your device simply doesn't support low latency Bluetooth connection
> 
> why then my enco free 3 headphones work fine low latency mode? it's definitely a problem with the ear app or whatever it's called.

How do you know it's not long latency? If you expect the short pause while switching that seem to be gone with last gen device

**Comment by Fan4eGGG** [comment]
> How do you know it's not long latency? 

wdym? i see that when i turn on the LL mod in my enco's (_not depending on your ear web app, they have internal LL mode built in_) i see that immediately, for example, the audio track speeds up by a millisecond and seems to rewind. Also, I have tested it on websites and videos like "audio delay test" etc. but when I connect my Ear (a) and enable LL mode on your website or this app, nothing happens. but LL in Ear (a) on my phone works fine.

i hope i have explained it clearly.

**Comment by Lisra-git** [comment]
> > How do you know it's not long latency?
> 
> wdym? i see that when i turn on the LL mod in my enco's (_not depending on your ear web app, they have internal LL mode built in_) i see that immediately, for example, the audio track speeds up by a millisecond and seems to rewind. Also, I have tested it on websites and videos like "audio delay test" etc. but when I connect my Ear (a) and enable LL mode on your website or this app, nothing happens. but LL in Ear (a) on my phone works fine.
> 
> i hope i have explained it clearly.

nothing happen when using them on my phoen either, we're talking about ms of difference, not a whole second

**Comment by Fan4eGGG** [comment]
> nothing happen when using them on my phoen either, we're talking about ms of difference, not a whole second

Okay, apparently you don't know what I'm talking about at all. then tell me why LL may not work on my PC and how can I fix it?

**Comment by Fan4eGGG** [comment]
> > nothing happen when using them on my phoen either, we're talking about ms of difference, not a whole second
> 
> Okay, apparently you don't know what I'm talking about at all. then tell me why LL may not work on my PC and how can I fix it?

sooo, can u help me pls?
