### ISSUE TITLE
Support for CMF Buds

### ISSUE THREAD

**Issue by Swpn0neel** [radiance-project/ear-web#2]
Currently, the most affordable ear buds offering from Nothing, the CMF Buds, has no support in the site. It would be great if we can get support for it too!

**Comment by hotaru-hspr** [comment]
Saw a few assets related to the CMF Buds in the files, they're probably working on it.

**Comment by Lisra-git** [comment]
I don't have CMF Buds so I can't test/add compatibility to the platform right now, will try to get them later

**Comment by Lisra-git** [comment]
Solved https://github.com/radiance-project/ear-web/commit/92788fe1fdd8225ffc9783a19978b0fa266d1fc5
