### ISSUE TITLE
Add app to a different browser

### ISSUE THREAD

**Issue by Jojofern98** [radiance-project/ear-web#21]
Hi there!
I normally use firefox to work, and your app at the moment is not compatible with this browser. You think this is possible to add in the future? I would love to have this app working on the firefox browser, it would be a game changer for sure. Your work is amazing!

Thank you!
Best Regards,
Joana Fernandes

**Comment by Lisra-git** [comment]
> Hi there! I normally use firefox to work, and your app at the moment is not compatible with this browser. You think this is possible to add in the future? I would love to have this app working on the firefox browser, it would be a game changer for sure. Your work is amazing!
> 
> Thank you! Best Regards, Joana Fernandes

Hey
Unfortunately, WebSerial via SPP is a Chromium exclusive for the moment, that's up to Mozilla to add support for WebSerial over SPP which is something that have a small chance to happen.

**Comment by krystian3w** [comment]
https://addons.mozilla.org/addon/webserial-for-firefox/

https://github.com/kuba2k2/firefox-webserial

I just don't know if it still requires another polyfill for Bluetooth like you said in https://github.com/radiance-project/ear-web/issues/34#issuecomment-2657647466 to @Ravindra-sys and based on https://github.com/kuba2k2/firefox-webserial/issues/19.

---

fyi @nikogt4 @Kipp-ie Based on https://github.com/radiance-project/ear-web/issues/23

**Comment by krystian3w** [comment]
How about this: https://bugzilla.mozilla.org/show_bug.cgi?id=2029625
