### ISSUE TITLE
No compatible device found 

### ISSUE THREAD

**Issue by jeff136** [radiance-project/ear-web#24]
I have a nothing ear (open). It works fine on my CMF phone 1 but I can't connect to my laptop. When I use the ear(web) it shows No compatible device found even though I had turned on my bluetooth. 

![image](https://github.com/user-attachments/assets/853f92d1-272c-4990-a63d-d57a274c874b)

**Comment by LisraCalco** [comment]
Hey
You need to pair Ear (open) first on your laptop

**Comment by jeff136** [comment]
I can't pair my ear (open) with my laptop. All drivers are up to date. It just won't detect my Ear (Open)

**Comment by LisraCalco** [comment]
You have to put it in pairing mode first, with both buds in the case, press the pairing button until led start to blink and it should appear on your pc

**Comment by jeff136** [comment]
It works now thanks! I am sorry if I waste your time
