### ISSUE TITLE
Low level distortion with new Nothingear buds

### ISSUE THREAD

**Issue by TopperMcFly** [radiance-project/ear-web#27]
I just returned the Nothing 2024's because the audio had a very annoying low level garble when using the personal sound profile. I ran the test successfully multiple times. Each time, music was way too bright and there was a low level distortion present. This distortion was not present with the default profiles. Also, the advanced EQ causes an unacceptable volume drop. Ironically, the Nothing (a)'s and these sound best to me using the balanced selection. I do not understand why I can't seem to duplicate balanced with manual. I really wanted the wireless charging and advanced controls of the Nothings. I do love the sound and fit of the a's. Just a shame all the way around. So close, yet so far.

**Comment by Lisra-git** [comment]
Hey, this app is not related to Nothing support/product team.
I'll close this issue since it's not related to the app functionalities.

**Comment by TopperMcFly** [comment]
Hey, thanks?
