### ISSUE TITLE
Can't Connect on the CMF Buds Pro 2

### ISSUE THREAD

**Issue by ad1tya29** [radiance-project/ear-web#4]
Whenever I am trying to connect and then select Cmf Buds pro 2 from the devices list, nothing is happening. I am getting this error in the console.
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'base')
    at switchViewFromModelID (nothing_connected.js:8:57)
    at processSerial (nothing_connected.js:232:5)
    at scanNewDevicesSerial (nothing_connected.js:290:17)

**Comment by Lisra-git** [comment]
> Whenever I am trying to connect and then select Cmf Buds pro 2 from the devices list, nothing is happening. I am getting this error in the console. Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'base') at switchViewFromModelID (nothing_connected.js:8:57) at processSerial (nothing_connected.js:232:5) at scanNewDevicesSerial (nothing_connected.js:290:17)

Hey
It's possible that your product is not in the list yet
Can you send the 6 first character of the serial number and your buds color? 
Thanks

**Comment by Lisra-git** [comment]
Hey, this should be fixed with the latest update, please test and i'll close this issue

**Comment by ad1tya29** [comment]
serial number first 6 digits - 135182
buds color - dark grey
buds name - CMF Buds Pro 2

**Comment by Lisra-git** [comment]
Can you check if it work?

**Comment by ad1tya29** [comment]
It is working now in incognito tab of chrome, not when there are more than 1 tabs present

**Comment by Lisra-git** [comment]
Perfect, thanks for your report
