### ISSUE TITLE
can't connect my cmf buds pro

### ISSUE THREAD

**Issue by Prateek199866** [radiance-project/ear-web#5]
![image](https://github.com/user-attachments/assets/290c8ad8-06db-4e0a-90ca-c48e8ba3f638)

can't able to connect CMF Buds pro

**Comment by Lisra-git** [comment]
> ![image](https://private-user-images.githubusercontent.com/86560757/367487069-290c8ad8-06db-4e0a-90ca-c48e8ba3f638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDIwNTYsIm5iZiI6MTcyNjMwMTc1NiwicGF0aCI6Ii84NjU2MDc1Ny8zNjc0ODcwNjktMjkwYzhhZDgtMDZkYi00ZTBhLTkwY2EtYzQ4ZThiYTNmNjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzRjN2RkMGNhNTAxYTA4MWIxYmRlMWJiYTllMzg2MTIyNTgxMTYyZTk0MjhkYTZlYTQzZDJjNTJjYjg0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKiaB_PRNz2AR4P9PMt-81iUEzBBlOX-PbDLv_XpqzI)
> 
> can't able to connect CMF Buds pro

Hey
You should click on "Buds Pro" and you should be able to click on Connect button

**Comment by KitKats77** [comment]
> > ![image](https://private-user-images.githubusercontent.com/86560757/367487069-290c8ad8-06db-4e0a-90ca-c48e8ba3f638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDIwNTYsIm5iZiI6MTcyNjMwMTc1NiwicGF0aCI6Ii84NjU2MDc1Ny8zNjc0ODcwNjktMjkwYzhhZDgtMDZkYi00ZTBhLTkwY2EtYzQ4ZThiYTNmNjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzRjN2RkMGNhNTAxYTA4MWIxYmRlMWJiYTllMzg2MTIyNTgxMTYyZTk0MjhkYTZlYTQzZDJjNTJjYjg0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKiaB_PRNz2AR4P9PMt-81iUEzBBlOX-PbDLv_XpqzI)
> > can't able to connect CMF Buds pro
> 
> Hey You should click on "Buds Pro" and you should be able to click on Connect button

I have the same issue. I select "Buds Pro" from the list then hit "Connect" button but the list pop-up comes up again instead of connecting.

**Comment by Lisra-git** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/86560757/367487069-290c8ad8-06db-4e0a-90ca-c48e8ba3f638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDIwNTYsIm5iZiI6MTcyNjMwMTc1NiwicGF0aCI6Ii84NjU2MDc1Ny8zNjc0ODcwNjktMjkwYzhhZDgtMDZkYi00ZTBhLTkwY2EtYzQ4ZThiYTNmNjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzRjN2RkMGNhNTAxYTA4MWIxYmRlMWJiYTllMzg2MTIyNTgxMTYyZTk0MjhkYTZlYTQzZDJjNTJjYjg0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKiaB_PRNz2AR4P9PMt-81iUEzBBlOX-PbDLv_XpqzI)
> > > can't able to connect CMF Buds pro
> > 
> > 
> > Hey You should click on "Buds Pro" and you should be able to click on Connect button
> 
> I have the same issue. I select "Buds Pro" from the list then hit "Connect" button but the list pops up again instead of connecting.

Do you see anything in F12 console?

**Comment by Prateek199866** [comment]
![image](https://github.com/user-attachments/assets/85670838-e5a0-4df1-bf61-16efe53309a8)

here it is after pressing F12
I don't what to do
showing paired but not conntecting

**Comment by Prateek199866** [comment]
![image](https://github.com/user-attachments/assets/cf91312a-1f47-4705-bb82-917a53cd672d)
from MS edge

**Comment by Lisra-git** [comment]
> ![image](https://private-user-images.githubusercontent.com/86560757/367564565-cf91312a-1f47-4705-bb82-917a53cd672d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzODc4MzAsIm5iZiI6MTcyNjM4NzUzMCwicGF0aCI6Ii84NjU2MDc1Ny8zNjc1NjQ1NjUtY2Y5MTMxMmEtMWY0Ny00NzA1LWJiODItOTE3YTUzY2Q2NzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA4MDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTkxN2Q1MjEwMmZiZGY0ZGFlODA0MGQyNGQ2NmIwMTVjM2FlNTgzNGU4Nzk5OTM3ZDZkMmFlMTY0OTM0ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Yc59tSArv_bWRC59g6d67X4n4VludY-VMicYzfU_4Q) from MS edge

Can you send the first 6 character of your serial number and device color

**Comment by Lisra-git** [comment]
Seem like it was an issue with the "dark grey" variant, issue is now fixed, please test

**Comment by Prateek199866** [comment]
![image](https://github.com/user-attachments/assets/052ce891-7f59-4ff4-9d3f-79ac4f856cae)

thanks a lot 🙏
