### ISSUE TITLE
Chrime for android versione 129.0.6668.70 com.android.chrome not supported 

### ISSUE THREAD

**Issue by MarcoProcida** [radiance-project/ear-web#8]
Opening link https://earweb.bttl.xyz/ in Chrome and After installaing ear web I receive the error unsupported browser

**Comment by Lisra-git** [comment]
> Opening link https://earweb.bttl.xyz/ in Chrome and After installaing ear web I receive the error unsupported browser

That's correct, it's only supported on PC versions of Chrome based browser's

**Comment by mrbrickstar** [comment]
There's an official app on Android: https://play.google.com/store/apps/details?id=com.nothing.smartcenter

**Comment by MarcoProcida** [comment]
Tnaknk you, my mistake. Issue could be closed

**Comment by MarcoProcida** [comment]
Tnaknk you, my mistake. Issue could be closed
